---
ID: "0cec9f68-9aa2-4eff-9684-a98c88f8200a"
Parent: "411f24df-bb3e-4741-8dd4-38207b81f5b8"
Template: "411f24df-bb3e-4741-8dd4-38207b81f5b8"
Path: /sitecore/templates/Foundation/ImageCompression/_ImageCompressionGlobalSettings/__Standard Values
DB: master
SharedFields:
- ID: "0b4c8d6b-6960-45f6-ab53-0e6aad664230"
  Hint: EndpointKey
  Value: INSERT YOUR TINY PNG KEY HERE
- ID: "e6a3cde0-9913-4304-b114-e318ef685c62"
  Hint: EndpointURL
  Value: "https://api.tinify.com/shrink"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0fe28c4f-bc97-4fc7-8ae8-2655380e08ec"
      Hint: ImageCompressionButtonEnabled
      Type: Checkbox
      Value: 1
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: "20200329T110620:637210767800057991Z"
    - ID: "41182b5f-bc24-4f87-8097-15f09af7eec1"
      Hint: ImageCompressionInformationField
      Value: Keywords
    - ID: "47428684-081a-45b1-9e96-c3c25f11218f"
      Hint: ImageCompressionScheduledTaskEnabled
      Type: Checkbox
      Value: 1
    - ID: "c17828c5-895b-4fa2-a824-901431abf451"
      Hint: ImageCompressionEnabled
      Type: Checkbox
      Value: 1
